-- Step 1: Create Tables
CREATE TABLE DEPARTMENT (
  DEPT_ID NUMBER PRIMARY KEY, 
  DEPT_NAME VARCHAR2(30)
);
CREATE TABLE EMPLOYEE (
  EMP_ID NUMBER PRIMARY KEY, 
  NAME VARCHAR2(50), 
  DEPT_ID NUMBER, 
  SALARY NUMBER
);
-- Step 2: Insert Data
-- Departments
INSERT INTO DEPARTMENT 
VALUES 
  (1, 'CSE');
INSERT INTO DEPARTMENT 
VALUES 
  (2, 'EEE');
INSERT INTO DEPARTMENT 
VALUES 
  (3, 'BBA');
-- Employees
INSERT INTO EMPLOYEE 
VALUES 
  (101, 'Rahat Shahriar', 1, 50000);
INSERT INTO EMPLOYEE 
VALUES 
  (102, 'Mahabub Rahman', 2, 55000);
INSERT INTO EMPLOYEE 
VALUES 
  (103, 'Ijaj Hakim', 1, 60000);
INSERT INTO EMPLOYEE 
VALUES 
  (104, 'Munjarin Khan', 1, 52000);
INSERT INTO EMPLOYEE 
VALUES 
  (105, 'Abu Siddik', 2, 58000);
INSERT INTO EMPLOYEE 
VALUES 
  (106, 'New Employee', 4, 45000);
--
--DEPT_ID 4 does not exist COMMIT;
-- Step 3: SQL Joins
1.
INNER JOIN – Only matching DEPT_ID 
SELECT 
  E.NAME, 
  E.SALARY, 
  D.DEPT_NAME 
FROM 
  EMPLOYEE E 
  INNER JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID;
Output NAME SALARYDEPT_NAME Rahat Shahriar50000CSE Ijaj Hakim60000CSE Munjarin Khan52000CSE Mahabub Rahman55000EEE Abu Siddik58000EEE 2.
LEFT JOIN – All employees, 
even if no matching department 
SELECT 
  E.NAME, 
  E.SALARY, 
  D.DEPT_NAME 
FROM 
  EMPLOYEE E 
  LEFT JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID;
Output NAME SALARY DEPT_NAME Rahat Shahriar50000CSE Ijaj Hakim60000CSE Munjarin Khan52000CSEMahabub Rahman55000EEE Abu Siddik58000EEE New Employee45000NULL 3.
RIGHT JOIN – All departments, 
even if no employee belongs 
SELECT 
  E.NAME, 
  E.SALARY, 
  D.DEPT_NAME 
FROM 
  EMPLOYEE E 
  RIGHT JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID;
Output NAME SALARYDEPT_NAME Rahat Shahriar50000CSE Ijaj Hakim60000CSE Munjarin Khan52000CSE Mahabub Rahman55000EEE Abu Siddik58000EEE NULLNULLBBA 4.FULL 
OUTER JOIN – All employees 
and all departments 
SELECT 
  E.NAME, 
  E.SALARY, 
  D.DEPT_NAME 
FROM 
  EMPLOYEE E FULL 
  OUTER JOIN DEPARTMENT D ON E.DEPT_ID = D.DEPT_ID;
Output NAME SALARYDEPT_NAME Rahat Shahriar50000CSE Ijaj Hakim60000CSE Munjarin Khan52000CSE Mahabub Rahman55000EEE Abu Siddik58000EEE New Employee45000NULL NULLNULLBBA

